// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: control_plane.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // unique ID of the data-plane instance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ConfigSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                            // monotonically increasing version counter
	ConfigYaml    string                 `protobuf:"bytes,2,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`     // full serialised gateway config (YAML)
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                               // human-readable reason for this snapshot
	GeneratedAt   int64                  `protobuf:"varint,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // Unix timestamp (seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSnapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigSnapshot) GetConfigYaml() string {
	if x != nil {
		return x.ConfigYaml
	}
	return ""
}

func (x *ConfigSnapshot) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConfigSnapshot) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitiatedBy   string                 `protobuf:"bytes,1,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"` // e.g. "admin-api", "operator"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *ReloadRequest) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                              // non-empty when success == false
	NewVersion    uint64                 `protobuf:"varint,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"` // version of the snapshot that was broadcast
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *ReloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReloadResponse) GetNewVersion() uint64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

var File_control_plane_proto protoreflect.FileDescriptor

const file_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x13control_plane.proto\x12\x19stateform.controlplane.v1\"3\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x86\x01\n" +
	"\x0eConfigSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1f\n" +
	"\vconfig_yaml\x18\x02 \x01(\tR\n" +
	"configYaml\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\fgenerated_at\x18\x04 \x01(\x03R\vgeneratedAt\"2\n" +
	"\rReloadRequest\x12!\n" +
	"\finitiated_by\x18\x01 \x01(\tR\vinitiatedBy\"a\n" +
	"\x0eReloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\x04R\n" +
	"newVersion2\xdb\x01\n" +
	"\x13ControlPlaneService\x12e\n" +
	"\tSubscribe\x12+.stateform.controlplane.v1.SubscribeRequest\x1a).stateform.controlplane.v1.ConfigSnapshot0\x01\x12]\n" +
	"\x06Reload\x12(.stateform.controlplane.v1.ReloadRequest\x1a).stateform.controlplane.v1.ReloadResponseBEZCgithub.com/your-org/stateform/control-plane/proto/v1;controlplanev1b\x06proto3"

var (
	file_control_plane_proto_rawDescOnce sync.Once
	file_control_plane_proto_rawDescData []byte
)

func file_control_plane_proto_rawDescGZIP() []byte {
	file_control_plane_proto_rawDescOnce.Do(func() {
		file_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)))
	})
	return file_control_plane_proto_rawDescData
}

var file_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_control_plane_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: stateform.controlplane.v1.SubscribeRequest
	(*ConfigSnapshot)(nil),   // 1: stateform.controlplane.v1.ConfigSnapshot
	(*ReloadRequest)(nil),    // 2: stateform.controlplane.v1.ReloadRequest
	(*ReloadResponse)(nil),   // 3: stateform.controlplane.v1.ReloadResponse
}
var file_control_plane_proto_depIdxs = []int32{
	0, // 0: stateform.controlplane.v1.ControlPlaneService.Subscribe:input_type -> stateform.controlplane.v1.SubscribeRequest
	2, // 1: stateform.controlplane.v1.ControlPlaneService.Reload:input_type -> stateform.controlplane.v1.ReloadRequest
	1, // 2: stateform.controlplane.v1.ControlPlaneService.Subscribe:output_type -> stateform.controlplane.v1.ConfigSnapshot
	3, // 3: stateform.controlplane.v1.ControlPlaneService.Reload:output_type -> stateform.controlplane.v1.ReloadResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_plane_proto_init() }
func file_control_plane_proto_init() {
	if File_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_proto_goTypes,
		DependencyIndexes: file_control_plane_proto_depIdxs,
		MessageInfos:      file_control_plane_proto_msgTypes,
	}.Build()
	File_control_plane_proto = out.File
	file_control_plane_proto_goTypes = nil
	file_control_plane_proto_depIdxs = nil
}
